export const ANNOUNCEMENT_REQUEST = "ANNOUNCEMENT_REQUEST";
export const ANNOUNCEMENT_SUCCESS = "ANNOUNCEMENT_SUCCESS";
export const ANNOUNCEMENT_FAIL = "ANNOUNCEMENT_FAIL";

export const ANNOUNCEMENT_CREATE_REQUEST = "ANNOUNCEMENT_CREATE_REQUEST";
export const ANNOUNCEMENT_CREATE_SUCCESS = "ANNOUNCEMENT_CREATE_SUCCESS";
export const ANNOUNCEMENT_CREATE_FAIL = "ANNOUNCEMENT_CREATE_FAIL";
export const ANNOUNCEMENT_CREATE_RESET = "ANNOUNCEMENT_CREATE_RESET";

export const ANNOUNCEMENT_DELETE_REQUEST = "ANNOUNCEMENT_DELETE_REQUEST";
export const ANNOUNCEMENT_DELETE_SUCCESS = "ANNOUNCEMENT_DELETE_SUCCESS";
export const ANNOUNCEMENT_DELETE_FAIL = "ANNOUNCEMENT_DELETE_FAIL";