export const MEMBER_ATTENDANCE_CHECKIN_REQUEST = "MEMBER_ATTENDANCE_CHECKIN_REQUEST";
export const MEMBER_ATTENDANCE_CHECKIN_SUCCESS = "MEMBER_ATTENDANCE_CHECKIN_SUCCESS";
export const MEMBER_ATTENDANCE_CHECKIN_FAIL = "MEMBER_ATTENDANCE_CHECKIN_FAIL";
