export const DIETPLAN_REQUEST = "DIETPLAN_REQUEST";
export const DIETPLAN_SUCCESS = "DIETPLAN_SUCCESS";
export const DIETPLAN_FAIL = "DIETPLAN_FAIL";

export const DIETPLAN_CREATE_REQUEST = "DIETPLAN_CREATE_REQUEST";
export const DIETPLAN_CREATE_SUCCESS = "DIETPLAN_CREATE_SUCCESS";
export const DIETPLAN_CREATE_FAIL = "DIETPLAN_CREATE_FAIL";
export const DIETPLAN_CREATE_RESET = "DIETPLAN_CREATE_RESET";

export const DIETPLAN_UPDATE_REQUEST = "DIETPLAN_UPDATE_REQUEST";
export const DIETPLAN_UPDATE_SUCCESS = "DIETPLAN_UPDATE_SUCCESS";
export const DIETPLAN_UPDATE_FAIL = "DIETPLAN_UPDATE_FAIL";
export const DIETPLAN_UPDATE_RESET = "DIETPLAN_UPDATE_RESET";

export const DIETPLAN_DELETE_REQUEST = "DIETPLAN_DELETE_REQUEST";
export const DIETPLAN_DELETE_SUCCESS = "DIETPLAN_DELETE_SUCCESS";
export const DIETPLAN_DELETE_FAIL = "DIETPLAN_DELETE_FAIL";
