export const EQUIPMENT_REQUEST = "EQUIPMENT_REQUEST";
export const EQUIPMENT_SUCCESS = "EQUIPMENT_SUCCESS";
export const EQUIPMENT_FAIL = "EQUIPMENT_FAIL";

export const EQUIPMENT_CREATE_REQUEST = "EQUIPMENT_CREATE_REQUEST";
export const EQUIPMENT_CREATE_SUCCESS = "EQUIPMENT_CREATE_SUCCESS";
export const EQUIPMENT_CREATE_FAIL = "EQUIPMENT_CREATE_FAIL";
export const EQUIPMENT_CREATE_RESET = "EQUIPMENT_CREATE_RESET";

export const EQUIPMENT_UPDATE_REQUEST = "EQUIPMENT_UPDATE_REQUEST";
export const EQUIPMENT_UPDATE_SUCCESS = "EQUIPMENT_UPDATE_SUCCESS";
export const EQUIPMENT_UPDATE_FAIL = "EQUIPMENT_UPDATE_FAIL";
export const EQUIPMENT_UPDATE_RESET = "EQUIPMENT_UPDATE_RESET";

export const EQUIPMENT_DELETE_REQUEST = "EQUIPMENT_DELETE_REQUEST";
export const EQUIPMENT_DELETE_SUCCESS = "EQUIPMENT_DELETE_SUCCESS";
export const EQUIPMENT_DELETE_FAIL = "EQUIPMENT_DELETE_FAIL";