export const MEMBER_PROGRESS_UPDATE_REQUEST = "MEMBER_PROGRESS_UPDATE_REQUEST";
export const MEMBER_PROGRESS_UPDATE_SUCCESS = "MEMBER_PROGRESS_UPDATE_SUCCESS";
export const MEMBER_PROGRESS_UPDATE_FAIL = "MEMBER_PROGRESS_UPDATE_FAIL";