export const TRAINER_REQUEST = "TRAINER_REQUEST";
export const TRAINER_SUCCESS = "TRAINER_SUCCESS";
export const TRAINER_FAIL = "TRAINER_FAIL";

export const TRAINER_CREATE_REQUEST = "TRAINER_CREATE_REQUEST";
export const TRAINER_CREATE_SUCCESS = "TRAINER_CREATE_SUCCESS";
export const TRAINER_CREATE_FAIL = "TRAINER_CREATE_FAIL";
export const TRAINER_CREATE_RESET = "TRAINER_CREATE_RESET";

export const TRAINER_UPDATE_REQUEST = "TRAINER_UPDATE_REQUEST";
export const TRAINER_UPDATE_SUCCESS = "TRAINER_UPDATE_SUCCESS";
export const TRAINER_UPDATE_FAIL = "TRAINER_UPDATE_FAIL";
export const TRAINER_UPDATE_RESET = "TRAINER_UPDATE_RESET";

export const TRAINER_DELETE_REQUEST = "TRAINER_DELETE_REQUEST";
export const TRAINER_DELETE_SUCCESS = "TRAINER_DELETE_SUCCESS";
export const TRAINER_DELETE_FAIL = "TRAINER_DELETE_FAIL";
