export const WORKOUTPLAN_REQUEST = "WORKOUTPLAN_REQUEST";
export const WORKOUTPLAN_SUCCESS = "WORKOUTPLAN_SUCCESS";
export const WORKOUTPLAN_FAIL = "WORKOUTPLAN_FAIL";

export const WORKOUTPLAN_CREATE_REQUEST = "WORKOUTPLAN_CREATE_REQUEST";
export const WORKOUTPLAN_CREATE_SUCCESS = "WORKOUTPLAN_CREATE_SUCCESS";
export const WORKOUTPLAN_CREATE_FAIL = "WORKOUTPLAN_CREATE_FAIL";
export const WORKOUTPLAN_CREATE_RESET = "WORKOUTPLAN_CREATE_RESET";

export const WORKOUTPLAN_UPDATE_REQUEST = "WORKOUTPLAN_UPDATE_REQUEST";
export const WORKOUTPLAN_UPDATE_SUCCESS = "WORKOUTPLAN_UPDATE_SUCCESS";
export const WORKOUTPLAN_UPDATE_FAIL = "WORKOUTPLAN_UPDATE_FAIL";
export const WORKOUTPLAN_UPDATE_RESET = "WORKOUTPLAN_UPDATE_RESET";

export const WORKOUTPLAN_DELETE_REQUEST = "WORKOUTPLAN_DELETE_REQUEST";
export const WORKOUTPLAN_DELETE_SUCCESS = "WORKOUTPLAN_DELETE_SUCCESS";
export const WORKOUTPLAN_DELETE_FAIL = "WORKOUTPLAN_DELETE_FAIL";
